version: '3'
services:
  client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - 8081:8081
    depends_on:
      - storage-service
  storage-service:
    build: ./storage
    volumes:
      - ./storage:/app
    ports:
      - 8080:8080
