name: lab1_service
services:
  storage:
    container_name: storage
    build:
      context: ./storage
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    networks:
      - lublumamu
      - lublupapu
    environment:
      SPRING_PROFILES_ACTIVE: cluster
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    command: get 56
    ports:
      - 8091:8091
    networks:
      - lublumamu
  redis-master:
    container_name: redis-master
    image: redis
    networks:
      lublumamu:
        ipv4_address: 172.29.1.4
    ports:
      - 6380:6380
    volumes:
      - ./conf:/app
    command: redis-server /app/redis-master.conf
  redis-replica-0:
    container_name: redis-replica-0
    image: redis
    networks:
      lublumamu:
        ipv4_address: 172.29.1.5
    ports:
      - 6381:6381
    volumes:
      - ./conf:/app
    command: redis-server /app/redis-replica-0.conf
  redis-replica-1:
    container_name: redis-replica-1
    image: redis
    networks:
      lublumamu:
        ipv4_address: 172.29.1.6
    ports:
      - 6382:6382
    volumes:
      - ./conf:/app
    command: redis-server /app/redis-replica-1.conf
networks:
  lublumamu:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.1.0/16
          gateway: 172.29.1.1
  lublupapu:
    name: lublupapu
